check-npm-licenses:
  image: node:16
  script:
    - /bin/bash ./license-checker/npm-licenses.sh "MIT;ISC;Apache-2.0;0BSD;BSD-2-Clause;BSD-3-Clause;CC0-1.0;CC-BY-4.0;Unlicense"
  artifacts:
    when: always
    paths:
      - npm_license_summary.txt
      - npm_license_detailed.json
    expire_in: 3 days
    reports:
      junit:
        - npm_licenses.xml

check-composer-licenses:
  image: composer:2.1.6
  script:
    - /bin/bash ./license-checker/composer-licenses.sh "MIT;LGPL-2.1;BSD-3-Clause;LGPL-3.0;Apache-2.0"
  artifacts:
    when: always
    paths:
      - composer_license_summary.txt
      - composer_license_detailed.txt
    expire_in: 3 days
    reports:
      junit:
        - composer_licenses.xml
